### ISSUE TITLE
Sync from namespaces other than vcluster's

### ISSUE THREAD

**Issue by Symbianx** [loft-sh/vcluster-sdk#80]
Hello 👋 

I started looking at implementing a plugin to sync Ingress resources from the host cluster into the vcluster. 
Our goal is to configure with an env variable which namespaces should have their ingresses synced into the vcluster.

So I took a look at the [import-secrets](https://github.com/loft-sh/vcluster-sdk/tree/main/examples/import-secrets) example and implemented something similar for Ingress resources. I now noticed that the `IsManaged` method only gets called for Ingresses created in the namespace where vcluster is running while I expect all the ingresses to trigger it.

Is there a configuration I'm missing?

Thank you!

**Comment by facchettos** [comment]
No, the vcluster doesn't have the permission to list objects outside of its namespace by default, and with some options we can have some extended permissions, but not listing ingresses in other namespaces. We would recommend writing a custom controller for this, which would be independent from the vcluster itself
